### PR TITLE
Pub sub

### LINKED ISSUE #12: Make queue declaration expressive
Support expressive declaration and routing/binding keys in `queues.php`, for the different supported exchange types.

```php
Registrator::queue(queue_name, ...\Handler);

Registrator::subscribe(queue_name, ...\Handler, [$bindingKeys]);
```

Provide a default pub-sub implementation on the producer's side, and set additional parameters like mentioned above at the consumer's side.

Assure full customization for `Registrator::queue`

### LINKED ISSUE #20: Improve Rabbitmq error handling
Improve Rabbitmq error handling.
```php
try {
    $channel->exchange_declare($this->exchangeName, $this->exchangeType, $this->passive, $this->durable, $this->autoDelete);
    $channel->queue_declare($this->queueName, $this->passive, $this->durable, false, $this->autoDelete, false, $this->arguments);
} catch (\Exception $e) {
    throw new DeclarationMismatchException($e->getMessage(), $e->getCode(), $e->getFile(), $e->getLine(), $e->getTrace(), $e->getPrevious(), $e->getTraceAsString(), $this->compileParameters(),  $this->arguments);
}
```
Not all exceptions should be of Type `DeclarationMismatchException`.

Example, try declare an exchange with a wrong type.

DeclarationMismatchException is only caught in the app's `Handler::report()`.

### PR DESCRIPTION
**Pull request by KinaneD**
resolves #12 
resolves #20

### CODE REVIEW

File: src/Producer.php [hunk 1]
```diff
@@ -119,8 +120,7 @@ public function publish($data)
         try {
             $channel->exchange_declare($this->exchangeName, $this->exchangeType, $this->passive, $this->durable, $this->autoDelete);
         } catch (\Exception $e) {
-            throw new DeclarationMismatchException($e->getMessage(), $e->getCode(), $e->getFile(), $e->getLine(), $e->getTrace(), $e->getPrevious(), $e->getTraceAsString(), $this->compileParameters(), $this->arguments
-                    );
+            (new BowlerExceptionHandler(app(ExceptionHandler::class)))->handleServerException($e, $this->compileParameters());
```
Comment (KinaneD) [inline src/Producer.php]: inject BowlerExceptionHandler instad.

Comment (KinaneD) [inline src/Producer.php]: same goes in ConsumerCommand:listenToQueue()

File: src/Consumer.php [hunk 2]
```diff
@@ -146,31 +137,33 @@ public function listenToQueue($handlerClass, ExceptionHandler $exceptionHandler)
             $channel->queue_bind($this->queueName, $this->exchangeName);
         }
 
-        echo ' [*] Listening to Queue: ', $this->queueName, ' To exit press CTRL+C', "\n";
-
-        $handler = new $handlerClass();
+        // Instantiate Handler
+        $queueHandler = new $handlerClass();
```
Comment (KinaneD) [inline src/Consumer.php]: use app(...::class), so that if any user DI exists, it is resolved by ioc

File: src/Console/Commands/SubscribeCommand.php [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+class SubscribeCommand extends Command
+{
+    const TYPE = 'subscribe';
+
+    /**
+     * The console command name.
+     *
+     * @var string
+     */
+    protected $signature = 'bowler:subscribe
```
Comment (Mulkave) [inline src/Console/Commands/SubscribeCommand.php]: using verbs such as `subscribe` gives the impression that it will "run" something, such as `consume`. But when it comes to generators, it's better to use the `make` as means of consistency with Laravel (i.e. `bowler:make:queue` and `bowler:make:subscription` or a better name you can think of.

File: src/Exceptions/BowlerGeneralException.php [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+    protected $previous;
+    protected $traceAsString;
+    protected $parameters;
+
+    // Dead lettering arguments
+    protected $arguments;
+
+    public function __construct($message, $code, $file, $line, $trace, $previous, $traceAsString, $parameters = [], $arguments = [])
+    {
+        $this->message = $message;
```
Comment (Mulkave) [inline src/Exceptions/BowlerGeneralException.php]: use Parent as `parent::__construct($message, $code, $previous)` or simply pass `$e` as is and let the `Exception` do the work.

File: src/Exceptions/Handler.php [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+     * @param \Exception $e
+     * @param array      $parameters
+     * @param array      $arguments
+     *
+     * @return mix
+     */
+    public function handleServerException(\Exception $e, $parameters = [], $arguments = [])
+    {
+        if ($e instanceof AMQPProtocolChannelException) {
+            $e = new DeclarationMismatchException($e->getMessage(), $e->getCode(), $e->getFile(), $e->getLine(), $e->getTrace(), $e->getPrevious(), $e->getTraceAsString(), $parameters,  $arguments);
```
Comment (Mulkave) [inline src/Exceptions/Handler.php]: It should be sufficient to instantiate with `new DeclarationMismatchException($e)` instead of having to extract the data from the previous exception and manually pass them to the next one.

File: src/Producer.php [hunk 6]
```diff
@@ -111,21 +103,21 @@ public function __construct(Connection $connection, $exchangeName, $exchangeType
      * Publish a message to a specified exchange.
      *
      * @param string $data
+     * @param string $routingKey    The routing key used by the exchange to route messages to bounded queues.
      */
-    public function publish($data)
+    public function publish($data, $routingKey = null)
```
Comment (Mulkave) [inline src/Producer.php]: - use `send` for producer, and `publish` for pub-sub only.
- switch the order of the parameters and have data be optional. When publishing, one might only want to publish an event occurring without providing any data.

File: src/Traits/HelperTrait.php [hunk 7]
```diff
@@ -16,16 +16,16 @@ private function compileParameters()
     {
         $params = [
                 'queueName' => property_exists($this, 'queueName') ? $this->queueName : null,
-                'exchangeName' => $this->exchangeName,
-                'exchangeType' => $this->exchangeType,
-                'passive' => $this->passive,
-                'durable' => $this->durable,
-                'autoDelete' => $this->autoDelete,
-                'deliveryMode' => $this->deliveryMode,
+                'exchangeName' => property_exists($this, 'exchangeName') ? $this->exchangeName : null,
```
Comment (Mulkave) [inline src/Traits/HelperTrait.php]: rename trait to resemble exactly its job/responsibility.

File: src/handlerexample.php [hunk 8]
```diff
@@ -1,5 +1,43 @@
 <?php
 
-Registrator::queue('books', 'BooksHandler', ['type' => 'fanout']);
+/**
```
Comment (Mulkave) [inline src/handlerexample.php]: move to `/examples` directory.

File: src/Console/Commands/QueueCommand.php [hunk 9]
```diff
@@ -36,11 +40,11 @@ public function handle()
     {
         $handlerGenerator = new HandlerGenerator();
 
-        $queue = $this->argument('queue');
+        $queue = $this->argument('queueName');
```
Comment (KinaneD) [inline src/Console/Commands/QueueCommand.php]: I believe so, but it works the way it is O_o.

File: src/MessageBroker.php [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    /**
+     * Get message.
+     *
+     * @return PhpAmqpLib\Message\AMQPMessage
+     */
+    public function getMessage()
+    {
+        return $this->message;
```
Comment (aliissa) [inline src/MessageBroker.php]: return $this->msg;

File: src/Exceptions/UnregisteredQueueException.php [hunk 11]
```diff
@@ -0,0 +1,18 @@
...
+namespace Vinelab\Bowler\Exceptions;
+
+use Vinelab\Bowler\Exceptions\BowlerGeneralException;
+
+/**
+ * @author Kinane Domloje <kinane@vinelab.com>
+ */
+class UnregisteredQueueException extends BowlerGeneralException
+{
+    protected $message;
```
Comment (aliissa) [inline src/Exceptions/UnregisteredQueueException.php]: let's be consistent with variable names, $msg or $message

File: src/MessageBroker.php (hunk 10 above)
Comment (KinaneD) [inline src/MessageBroker.php]: yiii

File: src/Producer.php [hunk 12]
```diff
@@ -48,84 +41,83 @@ class Producer
...
 
         try {
             $channel->exchange_declare($this->exchangeName, $this->exchangeType, $this->passive, $this->durable, $this->autoDelete);
         } catch (\Exception $e) {
-            throw new DeclarationMismatchException($e->getMessage(), $e->getCode(), $e->getFile(), $e->getLine(), $e->getTrace(), $e->getPrevious(), $e->getTraceAsString(), $this->compileParameters(), $this->arguments
-                    );
+            app(BowlerExceptionHandler::class)->handleServerException($e, $this->compileParameters());
         }
 
         $msg = new AMQPMessage($data, ['delivery_mode' => $this->deliveryMode]);
```
Comment (harris21) [inline src/Producer.php]: Will this throw an exception if `$data` is **null**? Or what will happen in that case?

File: src/Producer.php [hunk 13]
```diff
@@ -48,84 +41,83 @@ class Producer
...
         try {
             $channel->exchange_declare($this->exchangeName, $this->exchangeType, $this->passive, $this->durable, $this->autoDelete);
         } catch (\Exception $e) {
-            throw new DeclarationMismatchException($e->getMessage(), $e->getCode(), $e->getFile(), $e->getLine(), $e->getTrace(), $e->getPrevious(), $e->getTraceAsString(), $this->compileParameters(), $this->arguments
-                    );
+            app(BowlerExceptionHandler::class)->handleServerException($e, $this->compileParameters());
         }
 
-        $msg = new AMQPMessage($data, ['delivery_mode' => $this->deliveryMode]);
+        $message = new AMQPMessage($data, ['delivery_mode' => $this->deliveryMode]);
```
Comment (harris21) [inline src/Producer.php]: Will this throw an exception if `$data` is **null**? Or what would happen in that case?

File: src/Producer.php (hunk 12 above)
Comment (KinaneD) [inline src/Producer.php]: No it doesn't, if set to null, the default php-amqp library defaults to empty string.

**Comment by KinaneD** [comment]
@harris21 @aliissa @Mulkave Done?

File: src/MessageBroker.php (hunk 10 above)
Comment (Mulkave) [inline src/MessageBroker.php]: 😂

File: src/Console/Commands/QueueCommand.php (hunk 9 above)
Comment (Mulkave) [inline src/Console/Commands/QueueCommand.php]: weird
